
services:
  postgres-service:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: '${DB_DATABASE:-postgres}'
      POSTGRES_USER: '${DB_USERNAME:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-1234}'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - "5432:5432"
    volumes:
      - ./database_data:/var/lib/postgresql/data
      - ./postgres_transferencias:/temp

volumes:
  postgres_data:
